### PR TITLE
Update tailwind css instructions

### PR DESCRIPTION
**Pull request by ghostdevv**

### CODE REVIEW

**Comment by ghostdevv** [comment]
No one merge this just yet, need to add some more commits

**Comment by ghostdevv** [comment]
I just ended up fully rewriting it

**Comment by jakobrosenberg** [comment]
Could you add a note that this is a community contribution? Feel free to add your name if you wish. 🙂

**Comment by ghostdevv** [comment]
Yes, one sec

**Comment by ghostdevv** [comment]
Done @jakobrosenberg

**Pull request merged**
